name: RBI Exchange Rate Update

on:
  schedule:
    - cron: "0 10 * * *"   # 3:30 PM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests lxml html5lib openpyxl

      - name: Run script
        run: python script.py

      - name: Commit updated file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add currency_rates.xlsx
          git commit -m "Update RBI rates" || echo "No changes"
          git push
